Freeyourgadget/Gadgetbridge

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandSupport.java
It works from the debug activity, since I am not sure about the value of
the ts argument, it always sets the current time.
Created pull request as as asked in https://github.com/Freeyourgadget/Gadgetbridge/issues/15
> Implement setting the time on the miband.

- app/src/main/assets/logback.xml
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/GBApplication.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandSupport.java
* no more ByteBuffer, but a fixed size byte array that gets flushed everytime it's needed
* log of activity data to a separate file (no DB integration yet)
* the size of the buffer must be a multiple of 3 (1 minute of data = 3 bytes) and 20 (the normal size of the chunks we get from the device)
* better logging and more comments in code
> Refactoring of the data ingestion method.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandSupport.java
Perhaps could fix the "data in the future" issue. I don't think it's enough, though.
> Do not allocate the buffer if there's no data available.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/ActivityDatabaseHandler.java
* reducing the used space
* reducing the time needed for inserts
> Get rid of the unused ID in the DB, this could help in:

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/ActivityDatabaseHandler.java
Fixed a typo that was causing a force close on database creation.
> Fix crash on startup

- app/src/main/assets/logback.xml
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/GBApplication.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandSupport.java
This partially reverts commit 8b268a676cea3e520abeb1a8bc8aaa46329b58dd
> Remove the activity log debug file.

- app/src/main/AndroidManifest.xml
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/BluetoothCommunicationService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/ControlCenter.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/EventHandler.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/GBAlarm.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/ServiceDeviceSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/AlarmDetails.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/ConfigureAlarms.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/adapter/GBAlarmListAdapter.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandConst.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/miband/MiBandSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/pebble/PebbleSupport.java
- app/src/main/res/layout/activity_alarm_details.xml
- app/src/main/res/layout/activity_configure_alarms.xml
- app/src/main/res/layout/alarm_item.xml
- app/src/main/res/menu/controlcenter_context.xml
- app/src/main/res/menu/menu_alarm_details.xml
- app/src/main/res/menu/menu_set_alarm.xml
- app/src/main/res/values/strings.xml
I had to rebase due to some spurious commits in my original branch :/
The alarm functionality for the miband is here. It's accessible via long-press on the device. The menu item is there also for the pebbles.
> Set alarms on device (miband)

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/EventHandler.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/impl/GBDeviceService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/NotificationKind.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/ServiceDeviceSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/MiBandSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleProtocol.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/serial/AbstractSerialDeviceSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/serial/GBDeviceProtocol.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/TestDeviceSupport.java
> Pebble: Set application icons for generic notifications

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/UserInfo.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/btle/BtLEQueue.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/DeviceInfo.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/MiBandSupport.java
Hi again. I implemented pairing support for MI1A.
> Pairing support for MI1A

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/DeviceInfo.java
Hi, fixed bug in checksum.
Found it when my second MI1A didn't wanted to pair :)
> Fix DeviceInfo checksum function.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/K9Receiver.java
This fixes a small misspelling in the exception notification for K-9 Mail.
> Fix misspelling in exception notification.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/GBApplication.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/SettingsActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/K9Receiver.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/PhoneCallReceiver.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/SMSReceiver.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/preferences.xml
I felt that Do Not Disturb was missing when using my Mi Band 1S.
I'm not used to develop for Android or with java but everything seems to work as expected.
Added a preference to make notifications comply with the Do Not Disturb mode.
Can handle sms and phone calls from priority senders when in Priority only mode, but not events or reminders.
> Detects if Do Not Disturb is in use

- README.md
Update README.md fix the link to the pebble wiki article
> Update README.md fix pebble wiki article

- app/src/main/res/values/strings.xml
> Fixed 'Activiy' typo in strings.xml

- app/build.gradle
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Service.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/MiBand2Support.java
Added miband2 connection support, now when you bound miband2, it need to tap to confirm. and we also do some key exchange to auth miband2, after auth, we can keep miband2 connection and get other gatt Characteristic value.
its on doing , now i just added the key exchange and tap confirm with band2, after connect, you can use nodic to get other Characteristic value
> Added miband2 connection support

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/DBHandler.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/DBHelper.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/DeviceCoordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/btle/AbstractBTLEDeviceSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/btle/BleNamesResolver.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/MiBand2Support.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/MiBandSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/FileUtils.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/Prefs.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/LoggingTest.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/TestBase.java
- gradle.properties
For more information, see #390
> Rollback gradle.properties

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/MiBandSupport.java
Simply removed some redundant lines.
> Removed duplicate if statement.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java
- Toffeed: https://f-droid.org/repository/browse/?fdid=me.jakelane.wrapperforfacebook
- Slimsocial: https://f-droid.org/repository/browse/?fdid=it.rignanese.leo.slimfacebook
- MaterialFBook: https://f-droid.org/repository/browse/?fdid=me.zeeroooo.materialfb
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Mark 3rd party facebook apps notifications as Facebook

- README.md
I know, merely worth the effort... but the outdated information about the Mi Band 2 in the README was bugging me and may confuse new users.
> Updated documentation ("Supported Devices" section, Mi Band 2 info)

- app/src/main/res/values-fr/strings.xml
Changed and added several French messages.
> French translation.

- README.md
I was trying to "bond" the band with Gadgetbridge , but it only worked after unpairing from MiFit app and later trying again on Gadgetbridge.
> Updated known issues for Mi Band

- README.md
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/liveview/LiveviewConstants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/liveview/LiveviewCoordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/liveview/LiveviewIoThread.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/liveview/LiveviewProtocol.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/liveview/LiveviewSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java
Working so far: stable connection, setting time and sending notifications.
Please check the following before merge:
> Liveview: Initial support for Liveview devices

- GBDaoGenerator/src/nodomain/freeyourgadget/gadgetbridge/daogen/GBDaoGenerator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/SampleProvider.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusConstants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusCoordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusSampleProvider.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSleepRecord.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java
This seems to be working and can provide basic support for the Zeband. I would like some feedback and testing.
Tested on a Zeblaze Zeband
Not all protocol already decoded, but we will try to find the rest.
Working
- text and call notifications
- setting most user data, date and time
- heart rate monitoring (some flaws in continuous mode)
On the todo list
- sleep monitoring
- calorie monitoring
- distance monitoring
Probably feasible
- Alarms
Not clear right now
- Firmware update
- Battery status
> Add preliminary support for HPlus devices: Zeblaze Zeband and others

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java
Small fix for a bug pointed by ivanovlev.
> HPlus: fixed bug setting current date

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusDataRecordDaySlot.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusDataRecordRealtime.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusHandlerThread.java
This PR will fix the display of todays steps and will ignore missing HeartRate values.
> HPlus: Fix bug related to steps and heart rate

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/DebugActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/impl/GBDeviceService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationServiceTestCase.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/TestDeviceService.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/LanguageUtilsTest.java
In process of discussion, first target was chaged to simple refactoring
> I just seen, that debug "Send" button doesn't use DeviceCommunicationService, so the transliteration does not apply. This is fix for it, manual call..
> Simplification of transliteration integration

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java
Change Device Type so that it is understood as a subtype of HPLUS
> HPlus: Change Makibes F68 device type

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/impl/GBDeviceService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/JavaExtensions.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java
GBDeviceService.**onSetCallState** dont have callSpec.name (it's null), just number, and name will found later, by DeviceCommunicationService.**getContactDisplayNameByNumber**
So
**getContactDisplayNameByNumber** Moved to GBDeviceService, fully filled callSpec created in GBDeviceService, added new EXTRA (EXTRA_CALL_DISPLAYNAME), put it to Intent and used it later in DeviceCommunicationService directly - as other EXTRA's
> Fix issue #522 : Transliterate Caller Name

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusConstants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusCoordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/MakibesF68Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java
Properly enable alarms in HPlus devices
Small cleanup to simplify synchronisation process among the different devices
> HPlus: Working alarms and small cleanup

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusConstants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java
Fixes Time and Date synchronization issues as described in #539
> HPlus: Fix time sync and Time format (12/24)

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusConstants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java
Clear alarms in the device if no compatible alarm is available
> HPlus: Clear Alarms

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/MusicPlaybackReceiver.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java
Made sure PowerAMP's intent bundle's data gets stored in the right
place. Capitalized a few log messages and removed a "c" from a
variable. Also stored the list of intents that should be handled in a
array to make the code look a bit prettier and easier to add new
intents.
> Music data handling improvements

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/MusicPlaybackReceiver.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/MusicStateSpec.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java
I don't see it used anywhere, but it might be useful to have that data too. Though as Pebbles do nothing with the data I can't verify it being 100% correct. (Squash merge is recommended again as it would keep the history cleaner)
> Extract music shuffle and repeat states and set the song progress to auto-update.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationServiceTestCase.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/LanguageUtilsTest.java
Sorry for all the merges, these are internal in my repository.
> Added Hebrew transliteration and tests

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/AbstractGBFragment.java
Absolutely trivial and unimportant. It's more a test that I'm using git and github correctly in a collaborative environment than anything else.
> Correct camel-case for mVisibleInActivity

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/DbManagementActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/ImportExportSharedPreferences.java
- app/src/main/res/values/strings.xml
i add function for import and export SharedPreferences setting
when export or import db execute export or import SharedPreferences
for blacklist i preload HashSet
> import export SharedPreferences

- app/src/main/res/layout/device_itemv2.xml
small fix handy when are shown more than 3 info
> Device info display

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractWeekChartFragment.java
small fix that improves the readability of the values on bar charts
> Font size bar chart

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/CalendarReceiver.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/CalendarEvents.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java
Discussion in Freeyourgadget/Gadgetbridge#98
> Basic calendar sync using additional receiver

- CHANGELOG.md
> Updated CHANGELOG.md formatting

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/ActivityAnalysis.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/ChartsActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/StatsChartFragment.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/XAxisValueFormatter.java
- app/src/main/res/layout/fragment_statschart.xml
- app/src/main/res/values/strings.xml
Here is a first version of speed zones statistics. Enhancements are welcome!
> initial version of speed zones tab

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Service.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandConst.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandPreferencesActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/MiBand2Support.java
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/miband_preferences.xml
Implements #484.
Tested on firmware 1.0.1.50.
> Mi Band 2: Rotate wrist to switch info

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Service.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandConst.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandPreferencesActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/MiBand2Support.java
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/values.xml
- app/src/main/res/xml/miband_preferences.xml
Allows the user to change what items are displayed on the Mi Band 2 screen.
Implements #472.
> Mi Band 2: Display item settings

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Service.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandConst.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandPreferencesActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/MiBand2Support.java
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/miband_preferences.xml
Allow the user to enable or disable the daily steps goal notification (#485)
> Mi Band 2: Goal notification

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java
Adds support for Greek Chars transliteration (to latin)
> greek transliteration map

- app/src/main/res/values/colors.xml
I adjusted the colors a bit to
1. match material colors
2. have a visible distinction between primary_dark and primarydark_dark
3. match the color used by the action bar and side drawer in dark theme
Before
After
> Adjust colors

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/NotificationType.java
Nice project you have here!
Please let me know if I'm missing something or if this should be merged someplace other than master. I'm not sure in what other files these constants should be added for other clients.
Tested on my device. Debug notifications in this screenshot here:
> Add Pebble notification icons for Gmail, Inbox, and Google Calendar.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Constants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/no1f1/No1F1Support.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java
- app/src/main/res/drawable/level_list_device.xml
Works: connecting, writing user data, reading firmware version and battery charge, finding device.
I already understand protocol for this device enough to implement alarms, heart rate measurement, activity and sleep data fetching. But before writing more code I would like someone to check if I am doing everything right. Never wrote software for Android before. And so I had to use code for other devices as reference without understanding it completely.
> Initial NO.1 F1 support.

- GBDaoGenerator/src/nodomain/freeyourgadget/gadgetbridge/daogen/GBDaoGenerator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Constants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1SampleProvider.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/no1f1/No1F1Support.java
I was able to successfully fetch and save steps data from device. And they are showing correctly in the "Steps a week" tab. But graph "Your steps and activity" is empty.
Then I tried to override getAllActivitySamples to return data split by minutes instead of hours, like @ashimokawa suggested. But graph is still empty. I probably missed something important. Could you please look into my code?
> NO.1 F1 steps data

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/no1f1/No1F1Support.java
I am still not very confident in my code. So I will continue to make separate pull requests for each implemented feature instead of making a lot of changes at once.
Fetching and displaying sleep data now works but check to distinguish between light and deep sleep is very rudimentary. And there is no detection of awake time so total displayed sleep time is too high.
This device does not make any data analysis, all had to be done by an app. But before trying to come up with algorithm for it I want to implement fetching of heart rate data to have as much data to work with as possible.
> NO.1 F1: fetch sleep data.

- GBDaoGenerator/src/nodomain/freeyourgadget/gadgetbridge/daogen/GBDaoGenerator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/schema/GadgetbridgeUpdate_17.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Constants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/no1f1/No1F1Support.java
Implemented handling of real time heart rate data and fetching results of periodic measurements.
> NO.1 F1: Support for heart rate measurement.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/EXRIZUK8Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java
The device is compatible to HPLUS protocol.
Working:
- Alarm
- Fetch data from the device, such as heart rate, stored measurement data, stepcount, etc.
Not working:
- lost device command
- blood pressure (how to integrate these values?)
> Add support for EXRIZU K8 smartband.

- app/src/main/res/xml/miband_preferences.xml
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>
> Display button action settings as disabled when feature disabled

- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values/strings.xml
Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>
> Adjust strings to meet material guidlines

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/no1f1/No1F1Support.java
Measurement system for distance uses new global setting. And time format is set according to Android settings (the same implementation as for MiBand).
But I have a question. I have to reconnect to band for settings to take effect because they are sent during initialization. Is this just Gadgetbridge limitation? Or do I need to implement something for settings to be sent immediatly?
> NO.1 F1: Display settings.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Service.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandConst.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/MiBand2Support.java
Allow the user to change the distance unit displayed on the band.
Found it in Mi Fit settings, hadn't noticed it before. It's a simple setting / implementation.
> Mi Band 2: Change distance unit

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/no1f1/No1F1Support.java
I added CRC check (with error message for user), progress indicator and cleaned up code.
> NO.1 F1: Improvements in data fetching.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/LanguageUtilsTest.java
This mapping is roughly how Arabic speakers transliterate by hand, which you can read about [here](https://en.wikipedia.org/wiki/Arabic_chat_alphabet).
> Add transliteration for Arabic and Farsi.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java
There are at least two more telegram apps that could be added, like plus messenger, but I can't find the application ID of those right now.
> recognize telegram beta notifications

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java
* protonmail email
* challegram and plus messenger Telegram clients
> Recognize some more alternative apps

- app/release/output.json
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/impl/GBDeviceService.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/values.xml
- app/src/main/res/xml/preferences.xml
fix privacy caller ID selection
>  fix privacy caller ID selection

- GBDaoGenerator/src/nodomain/freeyourgadget/gadgetbridge/daogen/GBDaoGenerator.java
- README.md
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/xwatch/XWatchCoordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/xwatch/XWatchSampleProvider.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/xwatch/XWatchService.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/xwatch/XWatchSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java
- app/src/main/res/values/strings.xml
Basic support for the affordable Chinese Casio-like smart watches.
What does work:
* Activity syncing
* Multimedia control using the watch's button (one click play/pauses; double click skips to the next song/track)
What needs fixing:
* Intensity needs to be scaled down/up until a nice proportion
* Device must be set busy so the user cannot click sync again while syncing
What will be implemented next:
* Notifications
* Alarms
Will be fixing/implementing in my free time. Hope someone can make use of this :)
> Xwatch Basic Support

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/AppMessageHandlerSimplyLight.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleProtocol.java
Celsius forced as with other watchfaces #482
> Pebble: add support for weather in Simply Light watchface

- app/build.gradle
- gradle.properties
Basically fixes what 6a8700201f758ba189162a56747fffb12ffbf06c fixed without the disabling AAPT2.
> Re-enabled AAPT2

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/export/GPXExporter.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/amazfitbip/ActivityDetailsParser.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/operations/FetchSportsDetailsOperation.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DateTimeUtils.java
This PR incorporates a minimal set of tweaks to make heartrate export work on amazfit BIP, particularly for upload to Strava.com.
Changes include:
* Merge some of @swiss5555 changes relating to heart rate tracking
* Change the GPX XML to not output the src on every track point.
* Make sure the heart rate value is wrapped in a `TrackPointExtension` element.
I fully expect this PR to require some review before merging :)
> GPX export fixes for heartrate

- .travis.yml
- config/travis/validate_fastlane_metadata.sh
- fastlane/metadata/android/en-US/short_description.txt
> Check length of descriptions for F-Droid

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/Q8Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java
- app/src/main/res/values/strings.xml
Hello,
I have a Q8 device that is another HPlus. They all start with a Q8... name, so I added it as a new HPlus Subdevice. I tested it and seems to work well (as well as HPlus can).
Regards!
Alex
> Added support for Q8 devices

- app/src/main/res/values-ko/strings.xml
> Korean translate added

- app/src/main/AndroidManifest.xml
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/adapter/GBDeviceAdapterv2.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/watch9/Watch9CalibrationActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/watch9/Watch9Constants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/watch9/Watch9DeviceCoordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/watch9/Watch9PairingActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/watch9/Watch9DeviceSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/watch9/operations/InitOperation.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java
- app/src/main/res/layout/activity_watch9_calibration.xml
- app/src/main/res/layout/activity_watch9_pairing.xml
- app/src/main/res/layout/device_itemv2.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
Initial support for Watch 9 (hybrid smartwatch)
Working: 
- Notifications
- Alarms (maybe some further testing is needed to verify every alarm scenario)
- Setting step goal (progress can be checked on the watch face)
- Time calibration/sync
Some features are missing, but for now that is everything I found out.
> Watch 9: Initial support

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/jyou/TeclastH30Coordinator.java
Support added for H3 smart watch strap, which also uses JYou app to connect.
> Support added for H3 watch strap

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/LanguageUtilsTest.java
Added Lithuanian language transliteration.
> Adding Lithuanian transliteration

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/SettingsActivity.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/huami/miband3/MiBand3Coordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/huami/miband3/MiBand3Service.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandConst.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/miband3/MiBand3Support.java
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/values.xml
- app/src/main/res/xml/preferences.xml
Tested on firmware 1.4.0.6, probably not compatible with previous firmwares.
> Mi Band 3: Night Mode

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/GBApplication.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/Logging.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/DebugActivity.java
- app/src/main/res/layout/activity_debug.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
Add share log file. Tested on gmail, evernote, google drive. Issue #1146
Old PR: https://github.com/Freeyourgadget/Gadgetbridge/pull/1225/
> Add share log file 2.0. Issue #1146

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/BengaliLanguageUtils.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/LanguageUtilsTest.java
I've improved the Bengali transliteration using a regex-based approach which takes care of some corner cases, produces a more ITRANS-like and readable transliterated text.
> Better Bengali transliteration.

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/RtlUtils.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationServiceTestCase.java
In addition to https://github.com/Freeyourgadget/Gadgetbridge/pull/1233
> Rtl support: Add missing Persian letters + fix bug

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java
- app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/LanguageUtilsTest.java
I have reverted back Persian transliteration to remove the conflict with Arabic. However, some missing characters are now replaced. Hope it solves the test issue now.
> Persian transliteration

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractChartFragment.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/LiveActivityFragment.java
- app/src/main/res/layout/fragment_live_activity.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
Show current / max heart rate. Ignore heart rate < user settings. Invisible button bar into LiveActivity. Auto scale totalStepsChart. Fix time x axis history chart. Draw total and per minute steps. Set limit on per minute chart by user settings.
Clear history by #1241
> Enhancement LiveActivityFragment (2)

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/AbstractDeviceSupport.java
I can't reproduce the crash, but this should fix it.
> Start new activity with FLAG_ACTIVITY_NEW_TASK (fixes #1306)

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/MakibesF68Coordinator.java
Don't display KIA Sportage in the list of devices
> Avoid KIA Sportage appearing in the list of devices

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/AppMessageHandlerM7S.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/AppMessageHandlerObsidian.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/AppMessageHandlerRealWeather.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/AppMessageHandlerYWeather.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleProtocol.java
This pull request adds rudimentary weather support for the popular pebble watchfaces RealWeather and YWeather. Also, it fixes a bunch of typos.
> Pebble: add weather support for popular watchfaces

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/casiogb6900/CasioGB6900Constants.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/casiogb6900/CasioGB6900DeviceCoordinator.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/casiogb6900/CasioGATTServer.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/casiogb6900/CasioGB6900DeviceSupport.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/casiogb6900/CasioHandlerThread.java
This PR features improvements to the Casio support, in particular:
- Try to improve connection stability (configure BLE parameters, add a few waits)
- Add alarm configuration
- Improve find device service (now always beeps)
- Add support for GB-5600B
> [Casio] Improve Casio watch support

- README.md
Small update to the README, adding Weblate translation percentage badge.
> Add Weblate translation progress badge

- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractWeekChartFragment.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AngledLabelsChartRenderer.java
When 30days charts view is used, angle the barchart labels by -90°.
> adds custom renderer for better view of many columns

- CHANGELOG.md
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractChartFragment.java
- app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/SleepChartFragment.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/charts_preferences.xml
Addressing concern for night workers and those who prefer rolling 24h window. Also, changed split time to 12, as it is easier to explain and describe (Noon time).
> Add switch to set old/new style of sleep detection range
