app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/SleepChartActivity.java
Changed the colors of the Deep-/Light Sleep and Activity datasets.
* Deep sleep has been used as basic color,
* Light sleep is a color that is monochromatically analogous
* Activity is a color triadic to the basic one
=> Use colors that are easier on the eyes

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleProtocol.java
* Add a list of icons in the source code as I discovered them (invisible
for the user)
* Generic notification now use the correct icon instead of the SMS icon
=> Improve Pebble Time notifications icons

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java
Hi, as an owner of MI1A (in yesterdays comment I mistyped it as MI1S), I am willing to add support for it. So, here is my first baby step - try to pair :)
I also added notification toast when no device support is found. But it will be better to close PairingActivity and show error message.
After changes device still not pair but now there is an communication error. I have found that MI1A UserInfo differs from MI.
=> Initial support for newer MI devices.

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LimitedQueue.java
This commit fixes the following compilation error:
```
:app:compileDebugJavaWithJavac
/home/bob/dev/Gadgetbridge/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LimitedQueue.java:26:
error: incomparable types: Object and int
if (pair.first == id) {
^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:app:compileDebugJavaWithJavac FAILED
FAILURE: Build failed with an exception.
```
=> Fix #221 - Cast pair.first as integer

app/src/main/AndroidManifest.xml, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/SleepAlarmWidget.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/SettingsActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractChartFragment.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/SleepChartFragment.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/WeekStepsChartFragment.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/ActivityDatabaseHandler.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/schema/ActivityDBUpdate_6.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/UserInfo.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/SMSReceiver.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/ActivityUser.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/DatalogSessionHealthSleep.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/DatalogSessionHealthSteps.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java, app/src/main/res/layout/sleep_alarm_widget.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-v14/dimens.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/main/res/xml/sleep_alarm_widget_info.xml, app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/TestDeviceSupport.java
This pull request introduces a widget to allow a user to set an alarm using a single click and thus resolves  #237. The alarm is set according to the user's preferred sleep length (in hours).
Thanks @cpfeiffer for reviewing my code. I have implemented your comments.
=> Add widget to quickly set an alarm according to the user's preferred sleep length (in hours)

app/src/main/AndroidManifest.xml, app/src/main/assets/app_config/configure.html, app/src/main/assets/app_config/js/Uri.js, app/src/main/assets/app_config/js/gadgetbridge_boilerplate.js, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/AppManagerActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/ControlCenter.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/ExternalPebbleJSActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/EventHandler.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/pebble/PBWInstallHandler.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/pebble/PBWReader.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/impl/GBDeviceService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/ActivityUser.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/ServiceDeviceSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/MiBandSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleIoThread.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/PebbleUtils.java, app/src/main/res/layout/activity_external_pebble_js.xml, app/src/main/res/menu/appmanager_context.xml, app/src/main/res/values/strings.xml, app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/TestDeviceSupport.java, build.gradle
Needed steps before this code can be merged:
Limitations:
- The pebble configuration site must support the return_to parameter.
- inline configuration pages (data url) support has yet to be investigated
=> Use external browser for configuring pebble apps

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/AbstractSettingsActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandConst.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandPreferencesActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/MiBandSupport.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/miband_preferences.xml
Add a setting to preferences to enable support HearRate for Sleep detection.
Had some problems with the Preferences Framework due to using a Boolean Checkbox.
Settings are not synced on leaving the settings screen, only on reconnecting the device?
References https://github.com/Freeyourgadget/Gadgetbridge/issues/232
=> Heartrate sleep support Mi1S

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleIoThread.java
Sleep several seconds between reconnection attempts:
One second after first attempt, two after the second, and so on.
refs #89
=> Pebble: Smarter reconnection attempts

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandConst.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandDateConverter.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandPreferencesActivity.java, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/miband_preferences.xml
Mi-band firmware seems to gather sleep data only if sleep is initiated in a certain period of the day, probably between 10pm and some hour in the middle of the night. This means that shift workers, or just anyone that has the habit to go to sleep at a very different time can't use mi-band for sleep tracking.
This commit attempts to work around this limitation. It adds an option that specifies a device time offset in hours. All the times sent to the device are shifted by this offset and all the times received from the device are shifted "back". In this way mi-band thinks to be in a different time zone and gathers sleep data at different hours but data view on the app side is unaffected.
Example of usage: if you usually go to sleep at 6am, set the offset to -8 hours. At 6 am the device will …
=> Add support for shifting the device time by N hours

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/DebugActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/EventHandler.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/impl/GBDeviceService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/MusicStateSpec.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/ServiceDeviceSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/MiBandSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleProtocol.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/serial/AbstractSerialDeviceSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/serial/GBDeviceProtocol.java, app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/TestDeviceSupport.java
PocketCasts tells about its current media state via notifications. This
patch tries to parse incoming notifications from PocketCasts and if
successful tells the device about it. Currently supported are track and
artist.
I tested this with my (original) pebble. I do not know if this can be enhanced with track lenght and current progress as I was not able to squeeze this info out of the notification. Also, the device setMusicInfo would have to be improved to set the current progress. Both should be possible as the pebble android app apparently can do that.
=> Set music info for PocketCasts

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/DiscoveryActivity.java
When discovery gadget use Lollipop+ device, use new BTLE API instead of old general BT discovery.
=> Add new BTLE API for Lollipop+ user

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/NotificationType.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleProtocol.java
This PR moves the big switches that handle the notification types for Pebble to the existing `NotificationType` `enum` and an `AppNotificationType` class which is a singleton `HashMap`. 
I hope that this is will make it easier in the future to add support for new apps.
=> Revamp Notification types Pebble

CHANGELOG.md
The feature was not listed in the changelog. 0.15.1 is already released – not sure, if you want to add it afterwards, though...
=> Added (missing) battery status display feature for Mi Band 2 to the changelog

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java
K9 message body was not showing up in notifications since 0.15.0. This PR fixes that.
=> Show K9 message body in notifications

app/build.gradle, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/changelog_master.xml, app/src/main/res/xml/preferences.xml
Zeblaze ZeBand don't support russian language, so i found the great solution. Just transliterated to eng unsupported chars. Other symbols are not affected.
Method can be extended for other languages, it's very easy.
=> Transliterate unsupported Russian characters into English

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusConstants.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/StringUtils.java
The Zeband supports a subset of the GB2312, with some changes (may still require further research):
* up to char 175 it seems to use ASCII/Extended ASCII
* chars 161-163, 169, and 176-247 give access to the GB2312 table and the device will process two bytes at once. It means that there are many accented and special characters. Cyrillic is missing...
This pull request improves text display by: 
* incorporating the Transliteration work recently introduced.
* adjusting the remaining latin characters as some are still present. Because the transliteration table is specific for this device, it was not added to the LanguageUtils (alternative solutions are welcome). The result is that Cyrillic and accented Latin characters will be (mostly) displayed properly.
*  Improving Message notification …
=> HPlus: Improve display of new messages and phone calls

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusConstants.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusHealthSampleProvider.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/MakibesF68Coordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusDataRecordDaySlot.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusDataRecordRealtime.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusHandlerThread.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java
Adds support for the Makibes F68 Watch.
This is a subset of the HPlus devices with small changes. Most of the HPlus code is reused, with changes to consider both currently tested devices (Zeband and F68). There was some refactoring of existing code as my knowledge of the HPlus devices increased.
In both devices, if Continuous Heart Rate monitoring is not active, Activity Statistics will miss data. This will be addressed but I feel the code is ready for more testing as it enables these devices to connect.
=> HPlus: Support for Makibes F68

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java
Small fix to upper case scenario:
old variant:    "Щавелевый суп" > "SHHavelevyjj sup"
fixed variant: "Щавелевый суп" > "Shhavelevyjj sup"
=> Transliteration: capitalized just the first letter in the replacement

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractChartFragment.java
This partially "fixes" issue #442. The effect of the change is
purely cosmetic: deep sleep is (once again) dark blue, light sleep
is (once again) light blue.
=> Swap deep and light sleep colours in charts

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/BluetoothPairingRequestReceiver.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/btle/BleNamesResolver.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusDataRecordDaySlot.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusHandlerThread.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/hplus/HPlusSupport.java
Improve the connection process with HPlus devices and fixes #642 
Assumed that HPlus devices do not require pairing as they will reset to factory defaults when pairing.
Created method to block the pairing request if no bond is required by the coordinator.
Added periodic keep alive packets. 
This will be controlled by an option in a near future.
=> HPlus: Improve connection process

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/GB.java
- centralize the logic for skipping over unwanted notifications
- use *Compat methods wherever possible
- use unique and persistent ID (update notifications)
- switch to using BigText style by default (since we can now update existing notifications)
- for Pebble: delete and reinsert notification as updating is not possible
=> Refactor notification management

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/DoNotDisturb.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Coordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Service.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandConst.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandPreferencesActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/MiBand2Support.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/TimePreference.java, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/values.xml, app/src/main/res/xml/miband_preferences.xml
Allows the user to change the Mi Band 2 Do Not Disturb setting (implements #483).
I've added a new TimePreference (wasn't quite sure where to put it, it's in the util package), wrapping a TimePicker into a Preference.
I've also placed the new settings in a new screen in order to avoid cluttering the main one too much (some preferences already need reordering / regrouping).
Feedback is welcome, I can fix any issues or conflicts (specially if my other PR is merged first) and rebase this PR.
=> Mi Band 2: Do Not Disturb

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Coordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBand2Service.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandConst.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandPreferencesActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/MiBand2Support.java, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/miband_preferences.xml
Allow the user to enable inactivity warnings (implements #486)
The band supports 2 separate intervals for the inactivity warnings. Mi Fit has a do not disturb interval hard-coded from 12:00 to 14:00, I have made it modifiable as well.
I've also added the option to set the inactivity time threshold (which I think is the 3rd byte, it is not accurate to the minute, might need to test it a bit further, but seems to be close enough).
=> Mi Band 2: Inactivity Warnings

app/src/main/res/values/strings.xml
Since new chars has been added (https://github.com/Freeyourgadget/Gadgetbridge/commit/7f5aeb6ab1313395f45c88ffa8ef847b1d85d96a) it would be better not to mention specific languages here.
=> Update transliteration summary

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/receivers/GBMusicControlReceiver.java
Using the MediaSessionManager we can detect current playback sessions and getPackageName allowing playback control intents to be directed at the application currently playing media/last seen playing media.
This API feature is LOLLIPOP or greater only, however KITKAT functionality has been left unchanged.
On 5+ the ```Preferred Audioplayer``` preference will only be used if no playback sessions are detected.
Fixes [639](https://github.com/Freeyourgadget/Gadgetbridge/issues/639)
=> Support control of multiple media playback applications

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/NotificationType.java
**Change Contents:**
- Add a large number of notification icons missing from current version
- Update colors for existing icons to match Pebble colors exactly
- Add hooks for new icons
- Added new "Generic Phone" notification type
**Linked issue:** N/A
**Reason For Changes:**
Changes were made to add additional common icons and to add all icons from Pebble app into Gadgetbridge. Colors were also updated to match Pebble's coloring scheme exactly.
=> Update Pebble Notification Icons

app/build.gradle, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/DebugActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/impl/GBDeviceService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/NotificationSpec.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/NotificationType.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleProtocol.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/BitmapUtil.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/PebbleUtils.java, app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/PebbleUtilsTest.java
- Add a couple additional icon types
- Add Lighthouse (currently unused)
- Add Transit (public transportation app)
- Tweak the colors on existing icon types
- Implement logic to grab primary (vibrant) color from app logo
- The color will be used when displaying a notification for an app that does not have any configs bound to it.
- Alter NotificationType to support a color (named pebbleColor)
- Alter the Pebble notification poster to listen to the color from the notification
- Alter the DeviceCommunicationService to allow for color passthrough.
- Add logic to convert HEX or Integer representations of RGB888 colors to Pebble RGB222 format.
* #815: **Allow Automatic Notification Colors on Pebble**
See issue above. This commit will add in support for dynamic background colors for Pebble …
=> Add support for dynamic Pebble background colors

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java
- 'ґ' (Cyrillic Small Letter Ghe with Upturn U+0491) / 'Ґ' (Cyrillic Capital Letter Ghe with Upturn U+0490);
- 'є' (Cyrillic Small Letter Ukrainian Ie U+0454) / 'Є' (Cyrillic Capital Letter Ukrainian Ie U+0404);
- 'і' (Cyrillic Small Letter Byelorussian-Ukrainian I U+0456) / 'І' (Cyrillic Capital Letter Byelorussian-Ukrainian I U+0406);
- 'ї' (Cyrillic Small Letter Yi U+0457) / 'Ї' (Cyrillic Capital Letter Yi U+0407)
=> Add support for ukrainian characters

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java
It seems WeChat always mark its notifications as LocalOnly. The reason
may be to avoid double notifications when using Android Wear watches,
since WeChat has a standalone Android Wear app.
Do not ignore WeChat notifications even if they're marked as LocalOnly.
=> Allow WeChat notifications

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/Mi2FirmwareInfo.java
Firmware version 1.0.1.54 is marked as recommended on wiki (Mi Band
Firmware Information).
And it also seems to be working fine on my device. :)
=> Mi Band 2: whitelist firmware 1.0.1.54

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/SMSReceiver.java
When receive SMS message, instead of generating multiple notifications by
PDU size, after this change, there will be only one notification for
each sender.
=> Combine multipart SMS message into messages by sender

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java
As discussed in #883, this PR lets Gadgetbridge detect notifications coming from Facebook Messenger Lite as `NotificationType.FACEBOOK_MESSENGER`.
=> add Facebook Messenger Lite notification support

app/src/main/res/values-fr/strings.xml
- Correct "goute" with the correct word "goutte d'eau" ( https://fr.wikipedia.org/wiki/Goutte_(physique) )
- Add a space before an ":" (we place it in France)
=> Minor test fixes for the french translation

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java
Etar is a FOSS calendar app distributed on [F-Droid](https://f-droid.org/packages/ws.xsoh.etar/). I have not tested this change since I don't have the SDK set up.
=> Added Etar as calendar app type

app/src/main/AndroidManifest.xml, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/SettingsActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/DBHelper.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/database/PeriodicExporter.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/AutoStartReceiver.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/AndroidUtils.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/FileUtils.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/GB.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/GBPrefs.java, app/src/main/res/layout/activity_db_management.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Hi, first a disclaimer, I don't regularly program in Java and even less so for Android.
I try to implement an automatic export/backup of the database. The idea is to be able to specify where the database should be written every nth hour or so. Then, a sync tool like Syncthing picks it up and transfers it elsewhere, I import it into Influx DB or whatever and make nice graphs using Grafana or something similar. I think it is related to #553.
I started to add preferences, added an broadcast receiver, schedule intents using the AlarmManager and extended the export to an arbitrary URI so that the DB can be exported to any location a DocumentProvider supports.
There is still one big problem and probably a lot of room for improvement of the code style.
I'm unable to display the location of the …
=> First try at periodic db export

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/GB.java
Added a small spacer that makes the notification a lot nicer to read, before the device name and the text were just concatenated without any space in-between.
=> Improved notification text

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/SettingsActivity.java
I made a mistake in the code for the periodic export :(
Gadgetbridge crashes when you try to change the export interval. This should fix it. Sorry.
=> Fix crash when selecting automatic export interval

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java, app/src/test/java/nodomain/freeyourgadget/gadgetbridge/test/LanguageUtilsTest.java
Add ة, a normally-silent form of the letter ت that was missed when this
functionality was originally added.
=> Add ta marbutah to Arabic transliteration.

app/src/main/res/layout/activity_controlcenterv2_app_bar_main.xml, app/src/main/res/layout/activity_fragmentappmanager.xml
See issue #1041 
Also, removed elevation and pressedTranslationZ because `FloatingActionButton`s already have elevation
=> Change fab margin

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband2/Mi2NotificationStrategy.java
This fixes notification text not displaying when a short vibration
pattern is set.
If the notification text is sent while the icon is still visible
it is not displayed. We need to wait until it disapears (about 4 seconds)
=> Mi Band 2: wait at least 4s before sending notification text

app/src/main/res/values-fr/strings.xml
There was a typo in the French translations file. It has been corrected.
=> Fix typo in French translation

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/GBApplication.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/receivers/GBAutoFetchReceiver.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
#1116, requested a feature which makes the application able to automatically refresh the activity data without the need to open the application. I think this might be a possible solution, where the activity data is transferred when the screen is unlocked. There might be a possibility for improvement, where the snackbar tooltip could be removed, and a period between the syncs (since this will always update, when the phone is unlocked). 
I've been using this patch for a few weeks with the MiBand2 and it seems to work without major problems.
=> Auto sync feature

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/appmanager/AbstractAppManagerFragment.java
Adds `https://pebble-appstore.romanport.com/watchapps/0/?query={query}` as an Appstore Endpoint.
=> Add RomanPort's AppStore Endpoint

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/SettingsActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/receivers/GBAutoFetchReceiver.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
So this is a follow up from #1127, with a added option to block fetches within a time-period. 
The phone can be unlocked frequently, which would lead to GadgetBridge to fetch the activity data every time. This patch will disable the fetch for a period of time (set by the user). Also discovered that there was multiple GBAutoFetchReceiver active for one device, which should be removed now.
=> Allow the user to decide the interval between autofetches

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/impl/GBDeviceService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java
the NotificationSpec object, which describes a freshly posted notification, now contains the packageName of the app posting the notification in the sourceAppId field.
=> Fix missing sourceAppID field

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/adapter/GBDeviceAdapterv2.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/DeviceCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/UnknownDeviceCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/hplus/HPlusCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/huami/HuamiCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/jyou/TeclastH30Coordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/liveview/LiveviewCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/MiBandCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Coordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/pebble/PebbleCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/vibratissimo/VibratissimoCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/xwatch/XWatchCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/zetime/ZeTimeCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java
Not all devices should have the "find device" button.
Also, there's a missing break; in the createBTDeviceSupport switch.
=> Add missing break + Allow devices to not support being found

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/SettingsActivity.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/huami/miband3/MiBand3Service.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/miband3/MiBand3Support.java, app/src/main/res/xml/preferences.xml
Allows changing the Mi Band 3 display items.
The order currently depends on the iteration order of the `Set<String> pages`. The function already allows for the order to be set if a `List<String>` is provided with the proper order, for example, but I won't have the time to implement the UI for that any time soon, so this PR at least allows for the selection.
The 7th byte of COMMAND_CHANGE_SCREENS is always 0x06 (last position) probably reserved for some extra screen in the future, I tried to enable it without success.
=> Mi Band 3: Change display items

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Simple implementation that allows the user to specify a minimum time between notifications, preventing spam from chat apps.
Possible future improvements: 
- Per-app configuration?
- Reset on screen on? (optionally)
=> Support minimum time between notifications

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java
Fix duplicated DeviceType key introduced by the #1179 rebase.
=> Roidmi: fix duplicated DeviceType key

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/HeartRateUtils.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/AbstractChartFragment.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/ActivitySleepChartFragment.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/LiveActivityFragment.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/charts/SleepChartFragment.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/export/GPXExporter.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/GBPrefs.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Straightforward setting the minimum for the hr data to 10 instead of 0 to definitely eliminate zeroes and out of line hr data. Maybe we could even increase the minimum to around 40? What do you think?
Maximum value seems good to me.
<details>
<summary>Before / After</summary>
before:
after:
</details>
fixes #1173 
Would like to let #382 and #381 open since there could be more bogus stuff around according to the discussions.
=> remove incorrect HR data <10 from the graphs

app/src/main/AndroidManifest.xml, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/ControlCenterv2.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/PhoneCallReceiver.java
Fixes #1252
This fixes the caller id detection for Android 9. With the added `READ_CALL_LOG` permission, `PhoneCallReceiver` actually receives two broadcasts for each incoming call. The new guard in `PhoneCallReceiver` makes sure that only the broadcast which actually contains a populated `TelephonyManager.EXTRA_INCOMING_NUMBER` is processed. The other broadcast can safely be ignored according to the `TelephonyManager` documentation:
https://developer.android.com/reference/android/telephony/TelephonyManager#ACTION_PHONE_STATE_CHANGED
I could only test this change on Android 9.0 (Google Pixel), where it fixes #1252. Behavior on older Android versions needs to be tested before the merge.
=> Fix caller ID for incoming calls on Android 9

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/LanguageUtils.java
Persian (Farsi) transliteration was incomplete and most of the characters were proposed according to Arabic transliteration which would be confusing for Persians. I changed some of them and added new ones like question mark, etc.. Please note that Persian has several "z" and "s" since the language alphabet share a lot of similarity with Arabic. However, these are all pronounced the same way in Persian and it makes more sense to have the same character for all in each group.
=> Improved Persian transliteration

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java
Hello,
This very small PR adds support for p≡p application.
This app is a fork of K9 Mail with a slightly different design and a
built-in security integration feature.
More details: https://f-droid.org/en/packages/security.pEp/
The goal is to see the email icon when receiving this kind of
notifications.
Cheers,
Matt
=> Apps: add p≡p as generic email app

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/NotificationListener.java
It seems some apps like Telegram add a lot of Unicode Control sequences
for unknown reasons. Because these strings are set by external apps, it
is safer to sanitize them. For the moment, only Unicode control
sequences are stripped.
Fixes: #1344
=> notif: sanitize strings set by external apps

app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationServiceTestCase.java
Test _testRtlSupport_ in  _app/src/test/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationServiceTestCase.java_ fails
```
org.junit.ComparisonFailure: Rtl support fail! expected:<[תירבע English and]> but was:<[ English and
'bryth]>
at org.junit.Assert.assertEquals(Assert.java:115)
at nodomain.freeyourgadget.gadgetbridge.service.DeviceCommunicationServiceTestCase.testRtlSupport(DeviceCommunicationServiceTestCase.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```
because expected string doesn't suppose that transliteration is …
=> Fix RTL test

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/no1f1/No1F1Coordinator.java
I bought a cheap Chinese-made dummy/smart-watch. It apparently uses the same chip/protocol as implemented in No1F1 device support, but it reports with a different name, so we need to add it to the hardcoded name-based detection.
=> Enable No1F1 support for a Chinese clone

app/build.gradle, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/GBApplication.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/AbstractDeviceCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/DeviceCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/huami/amazfitcor/AmazfitCorCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/pebble/PebbleCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/amazfitbip/AmazfitBipSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/EmojiConverter.java
messages: convert emoji's to supported chars
Some devices don't support emoji's and display a series of `?` chars.
Instead of that, replace them by `:<emoji>:` text, e.g. `A 🐱` is
replaced by `A :cat:`.
This is done by using 'android-emojify' project and their
`EmojiUtils.shortCodify(text);` function.
For more details about this lib released under MIT license:
https://anitrend.github.io/android-emojify/
Note that for the moment, only amazfitbip's devices have this feature
because I don't know if the other watches can display Emoji. Simply use
the function mentioned here above to add this feature for other devices.
=> notif: convert emoji's to supported chars

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/GBApplication.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/EmojiConverter.java
The goal is not to slowdown the startup but also to do this initialisation only when it is needed.
Suggested-by: @cpfeiffer 
Note for @cpfeiffer : in your suggestion, you said:
> I would like to see this be done on demand, e.g. in `sanitizeNotifText()`
I moved this to the new EmojiConverter class to do everything related to the emoji there. I hope it  is OK for you :)
=> emoji: do a lazy initialisation

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/EmojiConverter.java
After having saw @cpfeiffer 's suggestion, I did this change, then I saw it was already done :)
Here only the init part is set as 'synchronized', very small optimisation but because this change is ready, why not sharing it :)
=> emoji: only the init can be sync

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/AppMessageHandlerM7S.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleProtocol.java
This patch adds rudimentary support for weather information on the M7S pebble watchface (https://github.com/cfg1/pebble-mss). It lacks support for user-configurable things like customizable weather strings / units.
=> Pebble M7S Watchface: add weather support 

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/casiogb6900/CasioGB6900Constants.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/casiogb6900/CasioGB6900DeviceCoordinator.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/DeviceType.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceSupportFactory.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/casiogb6900/CasioGATTServer.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/casiogb6900/CasioGATTThread.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/casiogb6900/CasioGB6900DeviceSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/casiogb6900/CasioHandlerThread.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/DeviceHelper.java, app/src/main/res/values/strings.xml
This PR adds initial support for the Casio GB-6900B watch. It was tested only on GB-X6900B (the only one I have), but it should work on some other models (GB-6900B, GB-5600B) as well. Other models might be easy to add (e.g. GBA-400), but I haven't got any other Casio devices to test with.
The watch has the ability to save power by turning off bluetooth after some inactivity and turn it back on afterwards. However, this is completely untested.
I'm not entirely sure if I got the Gatt server with the threading right, since I'm not very familiar with Android development. 
Looking forward to your comments!
=> Add initial support for Casio GB-6900B

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/util/EmojiConverter.java
This fixes the crashing on de-emojifying due to some unknown null. I think it's better at the moment to display `[?]` than to crash. I also added logging to the class to store strings that would otherwise crash the app in the logs.
```
Caused by: java.lang.NullPointerException: 
at io.wax911.emojify.EmojiUtils.shortCodify (EmojiUtils.java:222)
at ee.aegrel.gadgetbridge.util.EmojiConverter.convertAdvancedEmojiToAscii (EmojiConverter.java:84)
at ee.aegrel.gadgetbridge.util.EmojiConverter.convertUnicodeEmojiToAscii (EmojiConverter.java:90)
at ee.aegrel.gadgetbridge.service.DeviceCommunicationService.sanitizeNotifText (DeviceCommunicationService.java:367)
at ee.aegrel.gadgetbridge.service.DeviceCommunicationService.handleAction (DeviceCommunicationService.java:383)
at …
```
=> Added a try-catch to not crash on de-emojifying

app/src/main/AndroidManifest.xml
[This permission](https://developer.android.com/reference/android/Manifest.permission#FOREGROUND_SERVICE) [will be required](https://developer.android.com/about/versions/pie/android-9.0-migration#tya) if targetSDK is bumped, it doesn't hurt to make this change preemptively.
=> Added Foreground Service permission

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/impl/GBDeviceService.java
If a device contains a work profile and a contact saved in the work profile is calling, the name is not queried within Gadgetbridge. This PR also checks the work profile for matching contacts in case the number is not found.
=> Also check work profile for number lookup

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleActiveAppTracker.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleIoThread.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleKitSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/pebble/PebbleProtocol.java
There are several 3rd party Pebble apps that open up momentarily via PebbleKit (for example to pop up alert or notification). Those app start themselves via PebbleKit start and stop intents.
However, there is slight usability issue with those: If you have anything else open on the watch other than watchface (for example a running timer or sports tracker) when momentary app opens, previous app will be closed and after new app is finished, watch will return to the watchface. That can be annoying to the user.
With official Pebble app, this problem was solved by hooking into developer connection service and sniffing packets from there. It was very hacky and insecure. With Gadgetbridge, there is no developer connection, but since this app is open source, I figure I could add extension to the …
=> Add pebblekit extension for reopening last app

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/amazfitbip/AmazfitBipSupport.java, app/src/main/res/values/arrays.xml
Since Latin firmware 1.1.5.36 there are additional languages available:
- German
- Italian
- French
- Turkish
I tested switching between them without any problems.
=> Amazfit Bip: Add new latin languages

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/deviceevents/GBDeviceEventCallControl.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/PhoneCallReceiver.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/AbstractDeviceSupport.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/DeviceCommunicationService.java, app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/casiogb6900/CasioGB6900DeviceSupport.java
Muting an incoming call is an important feature for me which, unfortunately, Gadgetbridge is lacking. This PR adds support for it by temporarily changing the ringerMode to silent and restoring it back once the call has finished.
Although there are "silenceRinger" methods in ITelephony and TelecomManager, they are only available to system applications. Hence, the workaround is necessary.
The Casio implementation has been updated to add support for ignoring calls.
=> Add support for ignoring (muting) calls

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/zetime/ZeTimeDeviceSupport.java
calculate the correct UTC of different timezones and daylight savings.
=> ZeTime BUGFIX: Really fix the timestamps now for everyone, everywhere.

.travis.yml
Reason why build is broken now is because recently travis switched workers to Ubuntu Xenial by default. But Trusty is still available so for now I simply specified it in the config file.
Ultimately it will be better to adapt to recent distribution because support period of Trusty is ended. I will try it later.
=> Fixed travis build.

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/DbManagementActivity.java, app/src/main/res/layout/activity_db_management.xml, app/src/main/res/values/strings.xml
Simple addition which adds a button to the database management, to test the autoexport. It can help to try the auto export and perhaps also expose Permission Denial error.
summary:
- (conditionally) adds Test autoexport button
- moves several strings of activity_db_management into strings.xml
- adds few header labels to split the database management view
This button could have been added to Debug screen, but it feels more appropriate in DB management.
=> Add 'Run AutoExport Now' button to database management

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/activities/ControlCenterv2.java
It doesn't handle the issue #1696 directly, as i couldn't find the real cause (perhaps i didn't dig deep enough) but at least we can catch the error and let the app continue. So it fixes #1696 and also subsequent trials to open Changelog from the menu.
=> Catch crash during ChangeLog displaying

app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/huami/miband4/MiBand4Coordinator.java
There is custom emoji font for Mi Band 4 at myamazfit.ru. We should enable custom font setting.
=> Mi Band 4: Enable Emoji Font setting
